version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - /home/giovanitrevisol/databases/MongoDB:/data/db #note
      # - /home/giovani/Developer/databases/MongoDB:/data/db #pc
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    name: mongo-compose-network
    driver: bridge
    